APPLY() - CALCULATE PROJECT SALARY NEXT YEAR

In [153]:
import pandas as pd
import matplotlib.pyplot as plt
from datasets import load_dataset
#Load the dataset
dataset = load_dataset("lukebarousse/data_jobs")
df = dataset["train"].to_pandas()
#Data Cleanup
df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

In [154]:
df_salary = df[pd.notna(df['salary_year_avg'])].copy()
def projected_salary(salary):
    return salary * 1.03
df_salary['salary_year_inflated'] = df_salary['salary_year_avg'].apply(projected_salary)
df_salary[['salary_year_avg', 'salary_year_inflated']]

        salary_year_avg  salary_year_inflated
28             109500.0             112785.00
77             140000.0             144200.00
92             120000.0             123600.00
100            228222.0             235068.66
109             89000.0              91670.00
...                 ...                   ...
785624         139216.0             143392.48
785641         150000.0             154500.00
785648         221875.0             228531.25
785682         157500.0             162225.00
785692         157500.0             162225.00

[22003 rows x 2 columns]

In [155]:
df_salary['salary_year_inflated'] = df_salary['salary_year_avg'].apply(lambda salary: salary*1.03)
df_salary[['salary_year_avg', 'salary_year_inflated']]

        salary_year_avg  salary_year_inflated
28             109500.0             112785.00
77             140000.0             144200.00
92             120000.0             123600.00
100            228222.0             235068.66
109             89000.0              91670.00
...                 ...                   ...
785624         139216.0             143392.48
785641         150000.0             154500.00
785648         221875.0             228531.25
785682         157500.0             162225.00
785692         157500.0             162225.00

[22003 rows x 2 columns]

In [156]:
df_salary['salary_year_inflated'] = df_salary['salary_year_avg'] * 1.03
df_salary[['salary_year_avg', 'salary_year_inflated']]

        salary_year_avg  salary_year_inflated
28             109500.0             112785.00
77             140000.0             144200.00
92             120000.0             123600.00
100            228222.0             235068.66
109             89000.0              91670.00
...                 ...                   ...
785624         139216.0             143392.48
785641         150000.0             154500.00
785648         221875.0             228531.25
785682         157500.0             162225.00
785692         157500.0             162225.00

[22003 rows x 2 columns]

In [157]:
type(df['job_skills'])

pandas.Series

In [158]:
import ast

# 1. Turn NaNs into a string "[]"
df['job_skills'] = df['job_skills'].fillna('[]')

# 2. Now literal_eval will work on every row without crashing
df['job_skills'] = df['job_skills'].apply(ast.literal_eval)

In [159]:
# Run this to confirm it's already a list
type(df['job_skills'][0])

list

In [160]:
import ast

def clean_list(skill_list):
    # Only run literal_eval if the row is actually a string
    if isinstance(skill_list, str):
        return ast.literal_eval(skill_list)
    
    # If it's already a list or a NaN (float), just return it as-is
    return skill_list

df['job_skills'] = df['job_skills'].apply(clean_list)

In [161]:
# Converts the Series into a Python list
job_skills = df['job_skills'].tolist()

# Now you can check the type
print(type(job_skills)) 
# Output: <class 'list'>

<class 'list'>

In [162]:
import ast

# Use single brackets on the left to update the column directly
df['job_skills'] = df['job_skills'].apply(lambda x: ast.literal_eval(x) if isinstance(x, str) else x)

In [163]:
type(df['job_skills'])

pandas.Series

In [164]:
df_salary['salary_year_inflated'] = df_salary['salary_year_avg'].apply(lambda salary: salary * 1.03)
df_salary[['salary_year_avg', 'salary_year_inflated']]

        salary_year_avg  salary_year_inflated
28             109500.0             112785.00
77             140000.0             144200.00
92             120000.0             123600.00
100            228222.0             235068.66
109             89000.0              91670.00
...                 ...                   ...
785624         139216.0             143392.48
785641         150000.0             154500.00
785648         221875.0             228531.25
785682         157500.0             162225.00
785692         157500.0             162225.00

[22003 rows x 2 columns]

In [165]:
# Remove commas and convert to numeric
df_salary['salary_year_avg'] = pd.to_numeric(df_salary['salary_year_avg'].astype(str).str.replace(',', ''), errors='coerce')

# Now try your apply again
df_salary['salary_year_inflated'] = df_salary['salary_year_avg'].apply(lambda salary: salary * 1.03)

In [166]:
def projected_salary(row):
    if senior in row['job_title_short']:
        return row['salary_year_avg'] * 1.05
    else:
        return row['salary_year_avg'] * 1.03
df_salary[['job_title_short', 'salary_year_avg', 'salary_year_inflated']]

       job_title_short  salary_year_avg  salary_year_inflated
28      Data Scientist         109500.0             112785.00
77       Data Engineer         140000.0             144200.00
92       Data Engineer         120000.0             123600.00
100     Data Scientist         228222.0             235068.66
109       Data Analyst          89000.0              91670.00
...                ...              ...                   ...
785624   Data Engineer         139216.0             143392.48
785641   Data Engineer         150000.0             154500.00
785648  Data Scientist         221875.0             228531.25
785682  Data Scientist         157500.0             162225.00
785692  Data Scientist         157500.0             162225.00

[22003 rows x 3 columns]