In [2]:
import pandas as pd
import matplotlib.pyplot as plt
from datasets import load_dataset
#Load the dataset
dataset = load_dataset("lukebarousse/data_jobs")
df = dataset["train"].to_pandas()
#Data Cleanup
df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

c:\Users\rajay\anaconda3\envs\python_course\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

In [6]:
df.loc[:5, 'salary_rate' : 'salary_hour_avg']

  salary_rate  salary_year_avg  salary_hour_avg
0         NaN              NaN              NaN
1         NaN              NaN              NaN
2         NaN              NaN              NaN
3         NaN              NaN              NaN
4         NaN              NaN              NaN
5         NaN              NaN              NaN

In [11]:
median_salary_year = df['salary_year_avg'].median()

Median Salary Yearly: 115000.0

In [13]:
median_salary_hour = df['salary_hour_avg'].median()

Median Salary Hourly: 45.97999954223633

In [17]:
df_filled = df
df_filled['salary_year_avg'] = df_filled['salary_year_avg'].fillna(median_salary_year)
df_filled['salary_hour_avg'] = df_filled['salary_hour_avg'].fillna(median_salary_hour)

In [20]:
df_filled.loc[:5, 'salary_year_avg' : 'salary_hour_avg']

   salary_year_avg  salary_hour_avg
0         115000.0            45.98
1         115000.0            45.98
2         115000.0            45.98
3         115000.0            45.98
4         115000.0            45.98
5         115000.0            45.98

In [26]:
df_unique = df_filled
df_unique = df_unique.drop_duplicates()
print('Length before dropping duplicates:', len(df_filled))
print('Length after dropping duplicates:', len(df_unique))
print('Number of duplicates dropped:', len(df_filled) - len(df_unique))

Length before dropping duplicates: 785741
Length after dropping duplicates: 785640
Number of duplicates dropped: 101

In [43]:
df_unique = df_unique.drop_duplicates(subset=['job_title', 'company_name'])
print('Length before dropping duplicates:', len(df_filled))
print('Length after dropping duplicates:', len(df_unique))
print('Number of duplicates dropped:', len(df_filled) - len(df_unique))

Length before dropping duplicates: 785741
Length after dropping duplicates: 508042
Number of duplicates dropped: 277699